### ISSUE TITLE
Can Record<T> be removed from the public API

### ISSUE THREAD

**Issue by savannidgerinel** [luminescent-dreams/emseries#9]
Reported by @m0n0chr0m3:

Do you intend for Records (and DeletableRecords) to remain part of the public API? I.e., do you expect users of EmSeries to handle Record<T>s in their application logic, as opposed to handling only Ts, and occasionally a UniqueId? The way I see the general API of EmSeries evolving, a Series<T>' core query methods would return iterators over &T, or sometimes over (UniqueId, &T). Records would be an implementation detail which mostly just help serde do its thing (i.e., only what's currently named DeletableRecord would have much of a purpose). But perhaps I'm missing a use case. Can you clarify your intent?

**Comment by savannidgerinel** [comment]
This one is pretty hard for me to think about.

DeletableRecords should definitely be dropped from the public API. I use them internally only to represent the idea of an entry in the file log that gets deleted from the list of available records.

I think `Record` could be removed from the public API. What I need from users is just something that implements `Recordable`. I think `Record` may just be an artifact of my early Rust programming. I'll do some experiments with this in FitnessTrax and maybe make it part of an upcoming release.

**Comment by m0n0chr0m3** [comment]
`DeletableRecords` aren't in the public API, so that part is easy. As far as keeping the type internally, honestly, I like the way you designed it to leverage `serde`.

On the topic of removing `Record` from the public API: I created [a branch](https://github.com/m0n0chr0m3/emseries/commits/remove-records-from-api--issue-9) in my fork of EmSeries which removes the `Record` type completely. To gauge the impact on existing users — read: Fitnesstrax — I forked the Fitnesstrax repo and made [a commit](https://github.com/m0n0chr0m3/fitnesstrax/commit/0ec58bc9ba01c27dea8057f53757f65b9c8c83f1) porting Fitnesstrax to that variation on EmSeries.

At first sight, Fitnesstrax's architecture doesn't really enable it to benefit from the changes I made to EmSeries: many of Fitnesstrax's components store deep copies of what's in the database, so the iterators don't buy us much. The simple port presented in that commit simply materializes the list of IDs and the `TraxRecord` entries at the caller-side instead. In contrast, in my use case I get to use a `Series` as the singular source of 'truth'. Other parts of the code only get to retain IDs. With that approach, my changes make more sense: the entries themselves can be accessed by referencing the elements inside the `Series`, saving me a whole bunch of `clone`s.

Anyway, I thought this was an interesting exercise. Perhaps it's of use to you too.
